DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

OPTIM:
  NAME: "sgd"
  LR: 0.001
# 2022_4_29
# MAX_EPOCH: 40

# 2022_5_5
# MAX_EPOCH: 60

# 2022_5_8
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"